// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc_signup_user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignUpUserInput struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirm      string   `protobuf:"bytes,4,opt,name=passwordConfirm,proto3" json:"passwordConfirm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpUserInput) Reset()         { *m = SignUpUserInput{} }
func (m *SignUpUserInput) String() string { return proto.CompactTextString(m) }
func (*SignUpUserInput) ProtoMessage()    {}
func (*SignUpUserInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_e615baaf7557449e, []int{0}
}

func (m *SignUpUserInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpUserInput.Unmarshal(m, b)
}
func (m *SignUpUserInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpUserInput.Marshal(b, m, deterministic)
}
func (m *SignUpUserInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpUserInput.Merge(m, src)
}
func (m *SignUpUserInput) XXX_Size() int {
	return xxx_messageInfo_SignUpUserInput.Size(m)
}
func (m *SignUpUserInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpUserInput.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpUserInput proto.InternalMessageInfo

func (m *SignUpUserInput) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SignUpUserInput) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpUserInput) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignUpUserInput) GetPasswordConfirm() string {
	if m != nil {
		return m.PasswordConfirm
	}
	return ""
}

type SignUpUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpUserResponse) Reset()         { *m = SignUpUserResponse{} }
func (m *SignUpUserResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpUserResponse) ProtoMessage()    {}
func (*SignUpUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e615baaf7557449e, []int{1}
}

func (m *SignUpUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpUserResponse.Unmarshal(m, b)
}
func (m *SignUpUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpUserResponse.Marshal(b, m, deterministic)
}
func (m *SignUpUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpUserResponse.Merge(m, src)
}
func (m *SignUpUserResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpUserResponse.Size(m)
}
func (m *SignUpUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpUserResponse proto.InternalMessageInfo

func (m *SignUpUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*SignUpUserInput)(nil), "pb.SignUpUserInput")
	proto.RegisterType((*SignUpUserResponse)(nil), "pb.SignUpUserResponse")
}

func init() {
	proto.RegisterFile("rpc_signup_user.proto", fileDescriptor_e615baaf7557449e)
}

var fileDescriptor_e615baaf7557449e = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xd9, 0xba, 0x4a, 0x1d, 0x0f, 0x85, 0xa0, 0xb0, 0x14, 0x0f, 0xd2, 0x8b, 0xf5, 0xb0,
	0x59, 0xa8, 0xff, 0x40, 0x4f, 0x5e, 0x2b, 0xbd, 0x78, 0x29, 0xc9, 0x36, 0xa6, 0x01, 0x93, 0x19,
	0x26, 0x09, 0x9e, 0xfd, 0xe7, 0xe2, 0x88, 0x2e, 0xf4, 0xf6, 0xde, 0xf7, 0xe6, 0xf0, 0x0d, 0xdc,
	0x30, 0x8d, 0xfb, 0x1c, 0x7c, 0xaa, 0xb4, 0xaf, 0xd9, 0xb1, 0x26, 0xc6, 0x82, 0x6a, 0x46, 0x76,
	0x09, 0x53, 0x5f, 0x7d, 0x35, 0xb0, 0x78, 0x0d, 0x3e, 0xed, 0x68, 0x97, 0x1d, 0xbf, 0x24, 0xaa,
	0x45, 0x29, 0x68, 0x93, 0x89, 0xae, 0x6b, 0xee, 0x9a, 0xf5, 0xe5, 0x56, 0xb2, 0xba, 0x86, 0x73,
	0x17, 0x4d, 0xf8, 0xe8, 0x66, 0x02, 0x7f, 0x8b, 0x5a, 0xc2, 0x9c, 0x4c, 0xce, 0x9f, 0xc8, 0x87,
	0xee, 0x4c, 0x86, 0xff, 0xae, 0xd6, 0xb0, 0xf8, 0xcb, 0xcf, 0x98, 0xde, 0x03, 0xc7, 0xae, 0x95,
	0x93, 0x53, 0xbc, 0xda, 0x80, 0x9a, 0x14, 0xb6, 0x2e, 0x13, 0xa6, 0xec, 0xd4, 0x2d, 0xb4, 0x3f,
	0x9e, 0x62, 0x71, 0xb5, 0x99, 0x6b, 0xb2, 0x5a, 0x76, 0xa1, 0x4f, 0x0f, 0x6f, 0xf7, 0x3e, 0x94,
	0x63, 0xb5, 0x7a, 0xc4, 0x38, 0x90, 0x49, 0xf6, 0x68, 0x4a, 0x19, 0x3c, 0xf6, 0x3e, 0xa4, 0x7e,
	0xe4, 0x7a, 0xe8, 0x3d, 0x72, 0x1c, 0xc8, 0xda, 0x0b, 0xf9, 0xf4, 0xf1, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0x78, 0xec, 0x09, 0x10, 0x12, 0x01, 0x00, 0x00,
}
